on:
  workflow_dispatch:
    inputs:
      craftDocument:
        description: 'Craft Document Data'
        required: true
        type: string
jobs:
  print-craft-document-data:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Craft Document data: $CRAFT_DOCUMENT"
        env:
          CRAFT_DOCUMENT: ${{ github.event.inputs.craftDocument }}
          LEVEL: ${{ github.event.inputs.logLevel }}
          TAGS: ${{ github.event.inputs.tags }}
          ENVIRONMENT: ${{ github.event.inputs.environment }}
